### ISSUE TITLE
Option to specify time intervals for the rebuilds

### ISSUE THREAD

**Issue by kmoppel** [cybertec-postgresql/pg_squeeze#1]
Would be excellent to have somekind of optional extra parameter for specifying maintenance windows for starting rebuild tasks. A list of time
intervals comes to my mind first if I think about - smth like
'{00:00,03:00}'::time[]. This would give zB couple of hours of night time even
to rebuild jobs that would be started at 3 AM.

**Comment by ahouska** [comment]
Implemented in the master branch.

**Comment by kmoppel** [comment]
Hi! Managed to test the feature now and actually seems that the time interval selection is inverted. I had a time windows of '{18:30, 03:00}' and rebuild started exactly after the time interval ended. So I think ther'es something off with the range comparisons in the add_new_tasks() procedure.

My setup:

krl@postgres=# table squeeze.tables;
─[ RECORD 1 ]────┬──────────────────────────
id               │ 1
tabschema        │ public
tabname          │ pgbench_accounts
clustering_index │ ¤
rel_tablespace   │ ¤
ind_tablespaces  │ ¤
schedule         │ {18:30:00+02,03:00:00+02}
free_space_extra │ 10
min_size         │ 8
vacuum_max_age   │ 00:10:00
max_retry        │ 10
skip_analyze     │ f

krl@postgres=# table squeeze.log;
 tabschema │     tabname      │            started            │           finished            
───────────┼──────────────────┼───────────────────────────────┼───────────────────────────────
 public    │ pgbench_accounts │ 2017-01-19 03:00:47.554507+02 │ 2017-01-19 03:00:57.969594+02

**Comment by kmoppel** [comment]
closing the issue as everything works actually as expected - "squeeze.tables.schedule" column is actually a list of points when checking will be done if it is actually needed to start "squeezing".
