### ISSUE TITLE
Does not compile on CentOS 7

### ISSUE THREAD

**Issue by gabohuber** [cybertec-postgresql/pg_squeeze#10]
export PG_CONFIG=/usr/pgsql-9.6/bin/pg_config
make
rd -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I. -I./ -I/usr/pgsql-9.6/inclu
de/server -I/usr/pgsql-9.6/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pg_squeeze.o pg_squeeze.c
pg_squeeze.c: In function ‘check_prerequisites’:
pg_squeeze.c:735:23: error: ‘RELKIND_PARTITIONED_TABLE’ undeclared (first use in this function)
  if (form->relkind == RELKIND_PARTITIONED_TABLE)
                       ^
pg_squeeze.c:735:23: note: each undeclared identifier is reported only once for each function it appears in
pg_squeeze.c: In function ‘setup_decoding’:
pg_squeeze.c:851:10: error: too many arguments to function ‘CreateInitDecodingContext’
          NULL, NULL, NULL);
          ^
In file included from pg_squeeze.h:25:0,
                 from pg_squeeze.c:10:
/usr/pgsql-9.6/include/server/replication/logical.h:80:32: note: declared here
 extern LogicalDecodingContext *CreateInitDecodingContext(char *plugin,
                                ^
pg_squeeze.c:863:5: error: ‘LogicalDecodingContext’ has no member named ‘fast_forward’
  ctx->fast_forward = false;
     ^
pg_squeeze.c:880:2: error: too many arguments to function ‘MakeTupleTableSlot’
  dstate->tsslot = MakeTupleTableSlot(dstate->tupdesc_change);
  ^
In file included from /usr/pgsql-9.6/include/server/utils/tuplestore.h:34:0,
                 from /usr/pgsql-9.6/include/server/nodes/execnodes.h:25,
                 from pg_squeeze.h:23,
                 from pg_squeeze.c:10:
/usr/pgsql-9.6/include/server/executor/tuptable.h:142:24: note: declared here
 extern TupleTableSlot *MakeTupleTableSlot(void);
                        ^
pg_squeeze.c: In function ‘build_historic_snapshot’:
pg_squeeze.c:1795:2: warning: implicit declaration of function ‘SnapBuildInitialSnapshot’ [-Wimplicit-function-declaration]
  result = SnapBuildInitialSnapshot(builder);
  ^
pg_squeeze.c:1795:9: warning: assignment makes pointer from integer without a cast [enabled by default]
  result = SnapBuildInitialSnapshot(builder);
         ^
pg_squeeze.c: In function ‘perform_initial_load’:
pg_squeeze.c:1894:12: error: too many arguments to function ‘tuplesort_begin_cluster’
            false, false);
            ^
In file included from /usr/pgsql-9.6/include/server/nodes/execnodes.h:26:0,
                 from pg_squeeze.h:23,
                 from pg_squeeze.c:10:
/usr/pgsql-9.6/include/server/utils/tuplesort.h:66:24: note: declared here
 extern Tuplesortstate *tuplesort_begin_cluster(TupleDesc tupDesc,
                        ^
pg_squeeze.c:2100:5: error: too few arguments to function ‘tuplesort_getheaptuple’
     tup_out = tuplesort_getheaptuple(tuplesort, true);
     ^
In file included from /usr/pgsql-9.6/include/server/nodes/execnodes.h:26:0,
                 from pg_squeeze.h:23,
                 from pg_squeeze.c:10:
/usr/pgsql-9.6/include/server/utils/tuplesort.h:97:18: note: declared here
 extern HeapTuple tuplesort_getheaptuple(Tuplesortstate *state, bool forward,
                  ^
pg_squeeze.c: In function ‘create_transient_table’:
pg_squeeze.c:2246:3: error: too many arguments to function ‘heap_create_with_catalog’
   false, false, false, InvalidOid, NULL);
   ^
In file included from pg_squeeze.c:16:0:
/usr/pgsql-9.6/include/server/catalog/heap.h:54:12: note: declared here
 extern Oid heap_create_with_catalog(const char *relname,
            ^
pg_squeeze.c: In function ‘build_transient_indexes’:
pg_squeeze.c:2394:13: error: ‘INDEX_CREATE_IS_PRIMARY’ undeclared (first use in this function)
    flags |= INDEX_CREATE_IS_PRIMARY;
             ^
pg_squeeze.c:2508:12: warning: passing argument 7 of ‘index_create’ makes integer from pointer without a cast [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/pgsql-9.6/include/server/catalog/index.h:45:12: note: expected ‘Oid’ but argument is of type ‘struct IndexInfo *’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: warning: passing argument 8 of ‘index_create’ makes integer from pointer without a cast [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/pgsql-9.6/include/server/catalog/index.h:45:12: note: expected ‘Oid’ but argument is of type ‘struct List *’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: warning: passing argument 9 of ‘index_create’ makes pointer from integer without a cast [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/pgsql-9.6/include/server/catalog/index.h:45:12: note: expected ‘Oid *’ but argument is of type ‘Oid’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: warning: passing argument 10 of ‘index_create’ makes pointer from integer without a cast [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/pgsql-9.6/include/server/catalog/index.h:45:12: note: expected ‘Oid *’ but argument is of type ‘Oid’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: warning: passing argument 11 of ‘index_create’ from incompatible pointer type [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/pgsql-9.6/include/server/catalog/index.h:45:12: note: expected ‘int16 *’ but argument is of type ‘Oid *’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: warning: passing argument 12 of ‘index_create’ makes integer from pointer without a cast [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/pgsql-9.6/include/server/catalog/index.h:45:12: note: expected ‘Datum’ but argument is of type ‘Oid *’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: warning: passing argument 13 of ‘index_create’ makes integer from pointer without a cast [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/pgsql-9.6/include/server/catalog/index.h:45:12: note: expected ‘bool’ but argument is of type ‘int16 *’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: warning: passing argument 19 of ‘index_create’ makes integer from pointer without a cast [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/pgsql-9.6/include/server/catalog/index.h:45:12: note: expected ‘bool’ but argument is of type ‘void *’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: error: too few arguments to function ‘index_create’
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/pgsql-9.6/include/server/catalog/index.h:45:12: note: declared here
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c: In function ‘swap_relation_files’:
pg_squeeze.c:2808:2: warning: implicit declaration of function ‘CatalogTupleUpdateWithInfo’ [-Wimplicit-function-declaration]
  CatalogTupleUpdateWithInfo(relRelation, &reltup1->t_self, reltup1,
  ^
make: *** [pg_squeeze.o] Error 1

**Comment by ahouska** [comment]
I suspect you're trying to compile the master branch with PG 9.6. Please make sure that you have downloaded the correct package (https://github.com/cybertec-postgresql/pg_squeeze/releases).

**Comment by gabohuber** [comment]
His suspicion was correct.

Thanks!
