### ISSUE TITLE
standbydefs.h no such file or directory while 'make'

### ISSUE THREAD

**Issue by maxiwu** [cybertec-postgresql/pg_squeeze#11]
I have add PG_CONFIG to my environment path, the value is /usr/bin/pg_config
then I run 'make', it fails with error
pg_squeeze.c:42:33: fatal error storage/standbydefs.h: No such file or directory.

my postgresql version is 9.5, is it why I am missing that .h file?
I have already installed postgresql-server-dev-9.5 on my system.

**Comment by ahouska** [comment]
PG 9.5 is not supported. Please choose one of these releases: https://github.com/cybertec-postgresql/pg_squeeze/releases

If you want to use PG 9.6, you need at least 9.6.3 (you should have >= 9.6.3 anyway because some security bugs have been fixed in PG since 9.6.3).
