### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by MichaelDBA** [cybertec-postgresql/pg_squeeze#12]
got compile errors with latest git:
git clone https://github.com/cybertec-postgresql/pg_squeeze.git ./pg_squeeze
cd pg_squeeze
export PATH=/usr/lib/postgresql/10/bin:$PATH

root@MICHAELV8:/pg_squeeze# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -pie -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal -I/usr/include/x86_64-linux-gnu   -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pg_squeeze.o pg_squeeze.c
pg_squeeze.c: In function ‘setup_decoding’:
pg_squeeze.c:863:5: error: ‘LogicalDecodingContext’ has no member named ‘fast_forward’
  ctx->fast_forward = false;
     ^
pg_squeeze.c:880:2: error: too many arguments to function ‘MakeTupleTableSlot’
  dstate->tsslot = MakeTupleTableSlot(dstate->tupdesc_change);
  ^
In file included from /usr/include/postgresql/10/server/utils/tuplestore.h:34:0,
                 from /usr/include/postgresql/10/server/nodes/execnodes.h:28,
                 from pg_squeeze.h:23,
                 from pg_squeeze.c:10:
/usr/include/postgresql/10/server/executor/tuptable.h:142:24: note: declared here
 extern TupleTableSlot *MakeTupleTableSlot(void);

**Comment by ahouska** [comment]
Which branch are you trying to compile? If it's "master", then it's not expected to compile with PG 10. You need PG 11 or the PG master branch.

**Comment by ahouska** [comment]
The master branch is there primarily for pg_squeeze development. Users should get the appropriate version from https://github.com/cybertec-postgresql/pg_squeeze/releases
