### ISSUE TITLE
always occur operator for type 1043

### ISSUE THREAD

**Issue by JKeyZ** [cybertec-postgresql/pg_squeeze#13]
when worker run, always occur 
"Failed to find = operator for type 1043" , 
sql_state is XX000
table size is 16G, structure is:
uid character varying(128)
a     integer[]  
b     integer[]  
c     integer[]

**Comment by JKeyZ** [comment]
search log found error report:  syntax error at or near "ll"

**Comment by ahouska** [comment]
1. Which version of pg_squeeze is that?

2. What's the exact table definition, including indexes?

**Comment by JKeyZ** [comment]
pg_squeeze  is REL1_1_0 .
The table including index on array.

**Comment by JKeyZ** [comment]
also occur "Failed to find = operator for type 1043"
Before start worker, I had run  "ALTER EXTENSION pg_squeeze UPDATE" for update

**Comment by ahouska** [comment]
ALTER EXTENSION ... UPDATE will not apply the patch. You need to download the source code
https://github.com/cybertec-postgresql/pg_squeeze/archive/REL1_1.zip
and perform steps 1 through 5 from the "Installation" section of README.

**Comment by JKeyZ** [comment]
Before execute "alter extension update", I already make install. After update, pg show the info : NOTICE:  version "1.1" of extension "pg_squeeze" is already installed

**Comment by ahouska** [comment]
Have you restarted the instance (cluster) after the "make install"? If even that did not help, please send me the exact DDLs (CREATE TABLE, CREATE INDEX, ...) for the table that causes the error.

**Comment by JKeyZ** [comment]
yes, I already restarted the instance.
Can you give me the email? I send the ddls

**Comment by ahouska** [comment]
Please try https://github.com/cybertec-postgresql/pg_squeeze/archive/REL1_1.zip again.

**Comment by JKeyZ** [comment]
It's working.Thank you

**Comment by srikanth-medikonda** [comment]
@ahouska, are you the right person to reach about updating patch release 1.1.1 in pgdg repos? Or, is it PostgreSQL RPM Building Team: https://yum.postgresql.org/contact.php?

**Comment by drIceman** [comment]
Hi, what about making this fix for PG 9.6?
Because current version requires PG 10+
