### ISSUE TITLE
Use pg_squeeze for upgrading PKs from int4 to int8

### ISSUE THREAD

**Issue by NikolayS** [cybertec-postgresql/pg_squeeze#15]
There is a common problem: a table was created with int4 PK and, after some time, we have ~1B records in it, approaching int4's limit (2^31), so we need to change it to int8.

It would be great to use pg_squeeze for such a task. I'm not sure how difficult it would be to implement this although, right now this is just an idea – pg_repack also doesn't support it, while there is a significant demand in such feature.

**Comment by ahouska** [comment]
It's not trivial. Actually feature like this should be handled by ALTER TABLE command. If pg_squeeze implemented it, an obvious question is why it should not do many other things that ALTER TABLE does.
