### ISSUE TITLE
PG11 support

### ISSUE THREAD

**Issue by realknorke** [cybertec-postgresql/pg_squeeze#17]
IN GENERAL pg_squeeze (master branch) is working fine with PG11.

But from PG10 to PG11 the Background Worker struct changed and thus pg_stat_activity cannot work properly (e.g. the memory address for "background_type" of type char[] in pg11 is an int in pg10).

Please see the BackgroundWorker struct doc from [PG11](https://www.postgresql.org/docs/current/bgworker.html) vs. [PG10](https://www.postgresql.org/docs/10/bgworker.html).

Is it possible to make pg_squeeze PG11 compatible? There is no real alternative against index bloat (pg_repack comes with other problems)

**Comment by ahouska** [comment]
Is your problem that pg_stat_get_activity() showed garbage in the "backend_type" column? I've fixed that now, see https://github.com/cybertec-postgresql/pg_squeeze/archive/REL1_1.zip

Thanks for the report!

**Comment by realknorke** [comment]
Thank you very much for the patch. I instelled the 1_1 version some minutes ago. If there are still problems I'll let you know.

Yes, the backend_type columns was corrupted because the random memory was not UTF-8 compatible. ;)
The backend_type is now displayed as 'squeeze worker'. 

Thanks again! :+1:

**Comment by realknorke** [comment]
PS: maybe the application_name could also be set to "squeeze worker". Now its empty. But thats very low priority. :)

**Comment by ahouska** [comment]
The BackgroundWorker structure has no field to specify "application name", so there seems to be no straightforward way to set application_name for the worker. Note that application_name is typically used by client connections, however background workers are actually server components.
