### ISSUE TITLE
Support for different, yet compatible, DDL for the rewritten table

### ISSUE THREAD

**Issue by ahachete** [cybertec-postgresql/pg_squeeze#18]
This is related to, a generalization, of #15. That issue provides a good example of a good use case.

Since pg_squeeze uses logical replication, it is possible to use a destination table with a DDL potentially different from that of the source table, as long as they are compatible. You may add NULLABLE, DEFAULT columns or even modify data types.

Doing an ALTER TABLE and then an UPDATE is a very heavy operation for many environments, rendering it unacceptable. The current fix is to write complex logic for progressive batch updates which is very failure prone.

I cannot estimate difficulty of this, as mentioned before, but I'd say it would be a very welcome addition.

**Comment by ahouska** [comment]
I don't know how pg_squeeze could use parts of the ALTER TABLE functionality without copy&pasting big parts of PG source. And this is about ALTER TABLE if we want to treat catalog dependencies correctly.For example, if there's a CHECK constraint on a column whose data type should be changed by pg_squeeze, the constraint needs to be adjusted too. Or if there's an index on the column, catalog entry of that index needs to be changed.
