### ISSUE TITLE
About streaming replication

### ISSUE THREAD

**Issue by JKeyZ** [cybertec-postgresql/pg_squeeze#19]
Hello, I will build ha of pg by streaming replication mode.

If I change the parameter "wal_level" of settings from "logical" to "hot_standby" (and other relative parameters), will it work failed?

Do you have the doc for description about attentions?

**Comment by ahouska** [comment]
The "logical" value is needed. Lower level causes this error:
ERROR:  logical decoding requires wal_level >= logical

The wal_level setting is mentioned in README.

**Comment by JKeyZ** [comment]
Ok，thank you 

发自我的 iPhone
