### ISSUE TITLE
PG12 support

### ISSUE THREAD

**Issue by realknorke** [cybertec-postgresql/pg_squeeze#21]
Could you please add support for PG12?

Sadly the  changes from PG11 to PG12 are too many for me to provide you with a proper patch: my C skills are not good enough.

I'd like to help testing the new PG12-squeeze when its done. Thanks!

**Comment by realknorke** [comment]
Yes, the installation was easy, no problems here.
I'll start testing now (pg12 in general).

**Comment by realknorke** [comment]
Seems to work perfectly.
I'm using pg_squeeze on a db with several thousands UPSERTs per second (24/7) on partitioned tables with 4 replication slots to a slave db where pg_squeeze is running, too. I'm using the official PG docker image: 12beta2 (Debian 12~beta2-1.pgdg100+1)

No problems so far! :)

**Comment by realknorke** [comment]
Please feel free to resolve this issue, @ahouska :)

**Comment by ahouska** [comment]
I like issues like this, thanks :-) I hope it'll continue working.

**Comment by Dsolik** [comment]
Hi! Tell me, when can I download pg_squeeze for 12 versions of PostgreSQL from https://yum.postgresql.org?

**Comment by ahouska** [comment]
Yes, it should be there: https://yum.postgresql.org/news-packagelist.php

**Comment by Dsolik** [comment]
No rpm package for version PostgreSQL 12 https://yum.postgresql.org/12/redhat/rhel-7-x86_64/repoview/letter_p.group.html

**Comment by ahouska** [comment]
Indeed, it's missing there. I've reported that to packagers.

**Comment by ahouska** [comment]
The RPM appears to be in the repository now.

**Comment by Dsolik** [comment]
Thank you! pg_squeeze helps very much

**Comment by Gurpartap** [comment]
is there also a debian package for pg_squeeze with postgresql-12?


<details>
<summary>$ sudo apt search postgresql-12</summary>
<pre>
postgresql-12/buster-pgdg,now 12.2-2.pgdg100+1 amd64 [installed]
  object-relational SQL database, version 12 server

postgresql-12-asn1oid/buster-pgdg 1.2-3.pgdg100+1 amd64
  ASN.1 OID data type for PostgreSQL

postgresql-12-asn1oid-dbgsym/buster-pgdg 1.2-3.pgdg100+1 amd64
  debug symbols for postgresql-12-asn1oid

postgresql-12-bgw-replstatus/buster-pgdg 1.0.4.pgdg100+1 amd64
  report whether PostgreSQL node is master or standby

postgresql-12-bgw-replstatus-dbgsym/buster-pgdg 1.0.4.pgdg100+1 amd64
  debug symbols for postgresql-12-bgw-replstatus

postgresql-12-cron/buster-pgdg 1.2.0-1.pgdg100+1 amd64
  Run periodic jobs in PostgreSQL

postgresql-12-cron-dbgsym/buster-pgdg 1.2.0-1.pgdg100+1 amd64
  debug symbols for postgresql-12-cron

postgresql-12-cstore-fdw/buster-pgdg 1.7.0-1.pgdg100+1 amd64
  PostgreSQL foreign data wrapper for columnar storage

postgresql-12-cstore-fdw-dbgsym/buster-pgdg 1.7.0-1.pgdg100+1 amd64
  debug symbols for postgresql-12-cstore-fdw

postgresql-12-dbgsym/buster-pgdg 12.2-2.pgdg100+1 amd64
  debug symbols for postgresql-12

postgresql-12-debversion/buster-pgdg 1.1.1-3.pgdg100+1 amd64
  Debian version number type for PostgreSQL

postgresql-12-debversion-dbgsym/buster-pgdg 1.1.1-3.pgdg100+1 amd64
  debug symbols for postgresql-12-debversion

postgresql-12-dirtyread/buster-pgdg 2.2-1.pgdg100+1 amd64
  Read dead but unvacuumed tuples from a PostgreSQL relation

postgresql-12-dirtyread-dbgsym/buster-pgdg 2.2-1.pgdg100+1 amd64
  debug symbols for postgresql-12-dirtyread

postgresql-12-first-last-agg/buster-pgdg,now 0.1.4-4-gd63ea3b-2.pgdg100+1 amd64 [installed]
  PostgreSQL extension providing first and last aggregate functions

postgresql-12-first-last-agg-dbgsym/buster-pgdg 0.1.4-4-gd63ea3b-2.pgdg100+1 amd64
  debug symbols for postgresql-12-first-last-agg

postgresql-12-hll/buster-pgdg 2.14-1.pgdg100+1 amd64
  HyperLogLog extension for PostgreSQL

postgresql-12-hll-dbgsym/buster-pgdg 2.14-1.pgdg100+1 amd64
  debug symbols for postgresql-12-hll

postgresql-12-hypopg/buster-pgdg 1.1.3-1.pgdg100+1 amd64
  PostgreSQL extension adding support for hypothetical indexes.

postgresql-12-hypopg-dbgsym/buster-pgdg 1.1.3-1.pgdg100+1 amd64
  debug symbols for postgresql-12-hypopg

postgresql-12-icu-ext/buster-pgdg 1.5.1-2.pgdg100+1 amd64
  PostgreSQL extension exposing functionality from the ICU library

postgresql-12-icu-ext-dbgsym/buster-pgdg 1.5.1-2.pgdg100+1 amd64
  debug symbols for postgresql-12-icu-ext

postgresql-12-ip4r/buster-pgdg 2.4.1-2.pgdg100+1 amd64
  IPv4 and IPv6 types for PostgreSQL 12

postgresql-12-ip4r-dbgsym/buster-pgdg 2.4.1-2.pgdg100+1 amd64
  debug symbols for postgresql-12-ip4r

postgresql-12-jsquery/buster-pgdg 1.1.1-2.pgdg100+1 amd64
  PostgreSQL JSON query language with GIN indexing support

postgresql-12-jsquery-dbgsym/buster-pgdg 1.1.1-2.pgdg100+1 amd64
  debug symbols for postgresql-12-jsquery

postgresql-12-mimeo/buster-pgdg 1.5.1-7.pgdg100+1 all
  specialized, per-table replication between PostgreSQL instances

postgresql-12-mysql-fdw/buster-pgdg 2.5.3-1.pgdg100+1 amd64
  Postgres 12 Foreign Data Wrapper for MySQL

postgresql-12-mysql-fdw-dbgsym/buster-pgdg 2.5.3-1.pgdg100+1 amd64
  debug symbols for postgresql-12-mysql-fdw

postgresql-12-numeral/buster-pgdg 1.0-3.pgdg100+1 amd64
  numeral datatypes for PostgreSQL

postgresql-12-numeral-dbgsym/buster-pgdg 1.0-3.pgdg100+1 amd64
  debug symbols for postgresql-12-numeral

postgresql-12-ogr-fdw/buster-pgdg 1.0.9-1.pgdg100+1 amd64
  PostgreSQL foreign data wrapper for OGR

postgresql-12-ogr-fdw-dbgsym/buster-pgdg 1.0.9-1.pgdg100+1 amd64
  debug symbols for postgresql-12-ogr-fdw

postgresql-12-omnidb/buster-pgdg 2.17.0+ds-1.pgdg100+1 amd64
  PostgreSQL PL/pgSQL debugger extension for OmniDB

postgresql-12-omnidb-dbgsym/buster-pgdg 2.17.0+ds-1.pgdg100+1 amd64
  debug symbols for postgresql-12-omnidb

postgresql-12-orafce/buster-pgdg 3.9.0-1.pgdg100+1 amd64
  Oracle support functions for PostgreSQL 12

postgresql-12-orafce-dbgsym/buster-pgdg 3.9.0-1.pgdg100+1 amd64
  debug symbols for postgresql-12-orafce

postgresql-12-partman/buster-pgdg,now 4.3.0-1.pgdg100+1 amd64 [installed]
  PostgreSQL Partition Manager

postgresql-12-partman-dbgsym/buster-pgdg 4.3.0-1.pgdg100+1 amd64
  debug symbols for postgresql-12-partman

postgresql-12-periods/buster-pgdg 1.1-1.pgdg100+1 amd64
  PERIODs and SYSTEM VERSIONING for PostgreSQL

postgresql-12-periods-dbgsym/buster-pgdg 1.1-1.pgdg100+1 amd64
  debug symbols for postgresql-12-periods

postgresql-12-pg-catcheck/buster-pgdg 1.1.0-2.pgdg100+1 amd64
  Postgres system catalog checker

postgresql-12-pg-catcheck-dbgsym/buster-pgdg 1.1.0-2.pgdg100+1 amd64
  debug symbols for postgresql-12-pg-catcheck

postgresql-12-pg-checksums/buster-pgdg 1.0-3.pgdg100+1 amd64
  Activate/deactivate/verify PostgreSQL data checksums

postgresql-12-pg-checksums-dbgsym/buster-pgdg 1.0-3.pgdg100+1 amd64
  debug symbols for postgresql-12-pg-checksums

postgresql-12-pg-fact-loader/buster-pgdg 1.5.2-1.pgdg100+2 amd64
  Build fact tables asynchronously with Postgres

postgresql-12-pg-fact-loader-dbgsym/buster-pgdg 1.5.2-1.pgdg100+2 amd64
  debug symbols for postgresql-12-pg-fact-loader

postgresql-12-pg-qualstats/buster-pgdg 1.0.9-1.pgdg100+1 amd64
  PostgreSQL extension to gather statistics about predicates.

postgresql-12-pg-qualstats-dbgsym/buster-pgdg 1.0.9-1.pgdg100+1 amd64
  debug symbols for postgresql-12-pg-qualstats

postgresql-12-pg-stat-kcache/buster-pgdg 2.1.1-3.pgdg100+1 amd64
  PostgreSQL extension to gather per-query kernel statistics.

postgresql-12-pg-stat-kcache-dbgsym/buster-pgdg 2.1.1-3.pgdg100+1 amd64
  debug symbols for postgresql-12-pg-stat-kcache

postgresql-12-pgaudit/buster-pgdg 1.4.0-2.pgdg100+1 amd64
  PostgreSQL Audit Extension

postgresql-12-pgaudit-dbgsym/buster-pgdg 1.4.0-2.pgdg100+1 amd64
  debug symbols for postgresql-12-pgaudit

postgresql-12-pgextwlist/buster-pgdg 1.10-1.pgdg100+1 amd64
  PostgreSQL Extension Whitelisting

postgresql-12-pgextwlist-dbgsym/buster-pgdg 1.10-1.pgdg100+1 amd64
  debug symbols for postgresql-12-pgextwlist

postgresql-12-pgfincore/buster-pgdg 1.2.2-1.pgdg100+1 amd64
  set of PostgreSQL functions to manage blocks in memory

postgresql-12-pgfincore-dbgsym/buster-pgdg 1.2.2-1.pgdg100+1 amd64
  debug symbols for postgresql-12-pgfincore

postgresql-12-pgl-ddl-deploy/buster-pgdg 1.7.0-1.pgdg100+1 amd64
  Transparent DDL replication for PostgreSQL

postgresql-12-pgl-ddl-deploy-dbgsym/buster-pgdg 1.7.0-1.pgdg100+1 amd64
  debug symbols for postgresql-12-pgl-ddl-deploy

postgresql-12-pglogical/buster-pgdg 2.3.0-1.pgdg100+1 amd64
  Logical Replication Extension for PostgreSQL

postgresql-12-pglogical-dbgsym/buster-pgdg 2.3.0-1.pgdg100+1 amd64
  debug symbols for postgresql-12-pglogical

postgresql-12-pglogical-ticker/buster-pgdg 1.4.0-1.pgdg100+1 amd64
  Have time-based replication delay for pglogical

postgresql-12-pglogical-ticker-dbgsym/buster-pgdg 1.4.0-1.pgdg100+1 amd64
  debug symbols for postgresql-12-pglogical-ticker

postgresql-12-pgmemcache/buster-pgdg 2.3.0-7.pgdg100+1 amd64
  PostgreSQL interface to memcached

postgresql-12-pgmemcache-dbgsym/buster-pgdg 2.3.0-7.pgdg100+1 amd64
  debug symbols for postgresql-12-pgmemcache

postgresql-12-pgmp/buster-pgdg 1.0.4-2.pgdg100+1 amd64
  arbitrary precision integers and rationals for PostgreSQL 12

postgresql-12-pgmp-dbgsym/buster-pgdg 1.0.4-2.pgdg100+1 amd64
  debug symbols for postgresql-12-pgmp

postgresql-12-pgpool2/buster-pgdg 4.1.1-2.pgdg100+1 amd64
  connection pool server and replication proxy for PostgreSQL - modules

postgresql-12-pgpool2-dbgsym/buster-pgdg 4.1.1-2.pgdg100+1 amd64
  debug symbols for postgresql-12-pgpool2

postgresql-12-pgq-node/buster-pgdg 3.2.5-7.pgdg100+1 all
  Cascaded queueing on top of PgQ

postgresql-12-pgq3/buster-pgdg 3.2.6-34-g50068b2-2.pgdg100+1 amd64
  Generic queue for PostgreSQL

postgresql-12-pgq3-dbgsym/buster-pgdg 3.2.6-34-g50068b2-2.pgdg100+1 amd64
  debug symbols for postgresql-12-pgq3

postgresql-12-pgrouting/buster-pgdg 3.0.0~rc1-1.pgdg100+1 amd64
  Routing functionality support for PostgreSQL/PostGIS

postgresql-12-pgrouting-dbgsym/buster-pgdg 3.0.0~rc1-1.pgdg100+1 amd64
  debug symbols for postgresql-12-pgrouting

postgresql-12-pgrouting-doc/buster-pgdg 3.0.0~rc1-1.pgdg100+1 all
  Routing functionality support for PostgreSQL/PostGIS (Documentation)

postgresql-12-pgrouting-scripts/buster-pgdg 3.0.0~rc1-1.pgdg100+1 all
  Routing functionality support for PostgreSQL/PostGIS - SQL scripts

postgresql-12-pgtap/buster-pgdg 1.1.0-2.pgdg100+1 all
  Unit testing framework extension for PostgreSQL 12

postgresql-12-pldebugger/buster-pgdg 1:1.0-10-g2a298eb-2.pgdg100+1 amd64
  PostgreSQL pl/pgsql Debugger API

postgresql-12-pldebugger-dbgsym/buster-pgdg 1:1.0-10-g2a298eb-2.pgdg100+1 amd64
  debug symbols for postgresql-12-pldebugger

postgresql-12-pljava/buster-pgdg 1.5.5-3.pgdg100+1 amd64
  Java procedural language for PostgreSQL 12

postgresql-12-pljava-dbgsym/buster-pgdg 1.5.5-3.pgdg100+1 amd64
  debug symbols for postgresql-12-pljava

postgresql-12-pllua/buster-pgdg 1:2.0.4-2.pgdg100+1 amd64
  Lua procedural language for PostgreSQL 12

postgresql-12-pllua-dbgsym/buster-pgdg 1:2.0.4-2.pgdg100+1 amd64
  debug symbols for postgresql-12-pllua

postgresql-12-plproxy/buster-pgdg 2.9-2.pgdg100+1 amd64
  database partitioning system for PostgreSQL 12

postgresql-12-plproxy-dbgsym/buster-pgdg 2.9-2.pgdg100+1 amd64
  debug symbols for postgresql-12-plproxy

postgresql-12-plr/buster-pgdg 1:8.4-2.pgdg100+1 amd64
  Procedural language interface between PostgreSQL and R

postgresql-12-plr-dbgsym/buster-pgdg 1:8.4-2.pgdg100+1 amd64
  debug symbols for postgresql-12-plr

postgresql-12-plsh/buster-pgdg 1.20171014-4.pgdg100+1 amd64
  PL/sh procedural language for PostgreSQL 12

postgresql-12-plsh-dbgsym/buster-pgdg 1.20171014-4.pgdg100+1 amd64
  debug symbols for postgresql-12-plsh

postgresql-12-pointcloud/buster-pgdg 1.2.1-1.pgdg100+1 amd64
  PostgreSQL extension for storing point cloud (LIDAR) data

postgresql-12-pointcloud-dbgsym/buster-pgdg 1.2.1-1.pgdg100+1 amd64
  debug symbols for postgresql-12-pointcloud

postgresql-12-postgis-2.5/buster-pgdg 2.5.4+dfsg-1.pgdg100+1 amd64
  Geographic objects support for PostgreSQL 12

postgresql-12-postgis-2.5-dbgsym/buster-pgdg 2.5.4+dfsg-1.pgdg100+1 amd64
  debug symbols for postgresql-12-postgis-2.5

postgresql-12-postgis-2.5-scripts/buster-pgdg 2.5.4+dfsg-1.pgdg100+1 all
  Geographic objects support for PostgreSQL 12 -- SQL scripts

postgresql-12-postgis-3/buster-pgdg 3.0.1+dfsg-2.pgdg100+1 amd64
  Geographic objects support for PostgreSQL 12

postgresql-12-postgis-3-dbgsym/buster-pgdg 3.0.1+dfsg-2.pgdg100+1 amd64
  debug symbols for postgresql-12-postgis-3

postgresql-12-postgis-3-scripts/buster-pgdg 3.0.1+dfsg-2.pgdg100+1 all
  Geographic objects support for PostgreSQL 12 -- SQL scripts

postgresql-12-powa/buster-pgdg 3.2.0-2.pgdg100+1 amd64
  PostgreSQL Workload Analyzer -- PostgreSQL 12 extension

postgresql-12-powa-dbgsym/buster-pgdg 3.2.0-2.pgdg100+1 amd64
  debug symbols for postgresql-12-powa

postgresql-12-prefix/buster-pgdg 1.2.9-2.pgdg100+1 amd64
  Prefix Range module for PostgreSQL

postgresql-12-prefix-dbgsym/buster-pgdg 1.2.9-2.pgdg100+1 amd64
  debug symbols for postgresql-12-prefix

postgresql-12-preprepare/buster-pgdg 0.9-3.pgdg100+1 amd64
  pre prepare your PostgreSQL statements server side

postgresql-12-preprepare-dbgsym/buster-pgdg 0.9-3.pgdg100+1 amd64
  debug symbols for postgresql-12-preprepare
</pre>
</details>

**Comment by df7cb** [comment]
Debian packages are available from apt.postgresql.org now.
