### ISSUE TITLE
cancel pg_squeeze and delete temporary files

### ISSUE THREAD

**Issue by Antoine45514** [cybertec-postgresql/pg_squeeze#24]
Hello,

I have some question for you.
Is it possible to cancel a squeeze or limit the creation of temporary files ?
If the squeeze was stop brutally and temporary files was not delete automaticly  how do you delete files ?

**Comment by MichaelDBA** [comment]
Yeah i would like to know that too if it is safe to cancel a pgsqueeze full vacuum

**Comment by ahouska** [comment]
pg_squeeze can be cancelled.

As for temporary files (I assume you mean those used to sort data), pg_squeeze does nothing special. So it pg_squeeze makes the database server crash, the expected behavior is the same as if CLUSTER command crashed: temporary files are removed during cluster restart.

**Comment by kmoppel** [comment]
FYI - use pg_cancel_backend() to stop an active squeezing process. Note though that this also stops  the worker process so if you want to retry call squeeze.start_worker() manually.

@ahouska Would probably make sense also to add canceling support via pg_terminate_backend() as most PG activity monitoring tools use that function.

**Comment by ahouska** [comment]
@kmoppel  ok, I'll do that in the next version.

**Comment by kovmir** [comment]
Implemented in 4a5f97ed.
