### ISSUE TITLE
Processing starting immedietly when starting worker, regardless of squeeze.tables.schedule

### ISSUE THREAD

**Issue by airlocksniffer** [cybertec-postgresql/pg_squeeze#26]
Testing on some non-prod instances I'm finding as soon as I start the worker tables are processed immediately, even though I've specified in squeeze.tables.schedule to start at midnight.  Is this expected?

**Comment by ahouska** [comment]
Did you specify midnight as 0:00? I think it's o.k. to start processing because 0:00 is in the past at the moment the worker is launched. Does it help if you schedule the squeeze to run at 23:59?

**Comment by airlocksniffer** [comment]
Thanks @ahouska  that seemed to do the trick.
