### ISSUE TITLE
Squeeze temporary file

### ISSUE THREAD

**Issue by Dsolik** [cybertec-postgresql/pg_squeeze#28]
Hi! In the log of pg I see that process of squeeze creates temporary files when performing selec squeeze.squeeze_table... Which option can I increase so that temporary files are not created?

**Comment by ahouska** [comment]
pg_squeeze does not use temporary files explicitly, but it can cause the PG core to do so. I think the most obvious use case is that the data is sorted on disk before it's inserted into the new table. Thus maintenance_work_mem might be the setting to increase.

**Comment by Dsolik** [comment]
I increased the maintenance_work_mem parameter by a fraction of the generated temporary files, but this did not help, the files are equally created of the same size. What else can we do?

**Comment by kmoppel** [comment]
I think it's due to building of indexes...so you need to increase it even more to fit the table data + some extra margin. But for large enough tables it generally can't be avoided....
