### ISSUE TITLE
[Feature] Add possibility to manually launch one time squeezes

### ISSUE THREAD

**Issue by kmoppel** [cybertec-postgresql/pg_squeeze#30]
So maybe to have some nice function like squeeze.process_single_table($table_name, $timeout) that unconditionally (no bloat check) queues a rebuild.

**Comment by ahouska** [comment]
Doesn't the squeeze_table() function meet your requirements? It can be called directly w/o scheduling.

**Comment by kmoppel** [comment]
Ah thanks, my bad. Didn't look deeply enough...but would make sense to add some note on that to the README also.

**Comment by kmoppel** [comment]
Manual "squeeze" function signature:
`FUNCTION squeeze.squeeze_table(tabchema name, tabname name, clustering_index name, rel_tablespace name, ind_tablespaces name[])`

Sample execution:
`SELECT squeeze.squeeze_table('public', 'pgbench_accounts', null, null, null);`
