### ISSUE TITLE
worker_naptime parameter

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pg_squeeze#33]
Hello, 
i can not change worker_naptime
i always face this : 
ERROR:  parameter "squeeze.worker_naptime" cannot be changed now

thanks

**Comment by kmoppel** [comment]
This is expected. It's a SIGHUP level setting, i.e. you need to reload config (or restart the server).
```
localhost:5432 krl@postgres=# select name, context from pg_settings where name ~ 'worker_naptim';
          name          │ context 
────────────────────────┼─────────
 squeeze.worker_naptime │ sighup
(1 row)

```

**Comment by pmpetit** [comment]
So i change it in postgresql.conf ?
What is GUC parameter ?
GUC stand for ?
Thanks

**Comment by pmpetit** [comment]
According to me, the confusion  comes from  the readme

add entries like this to postgresql.conf file
	squeeze.worker_autostart = 'my_database your_database'
	squeeze.worker_role = postgres

and

consider setting "squeeze.max_xlock_time" GUC parameter. For
example

	SET squeeze.max_xlock_time TO 100;

so i thought i should use set to change "naptime"

**Comment by kmoppel** [comment]
@pmpetit  Yes, max_xlock_time param can be set anytime as it has the "user" context. GUC I think stands for Grand Unified Config but basically just means a config param. But yes this "squeeze.worker_naptime" requires ALTER SYSTEM or config file change + a reload.
