### ISSUE TITLE
Tasks being run outside of scheduled times

### ISSUE THREAD

**Issue by adamjforster** [cybertec-postgresql/pg_squeeze#36]
I recently built pg_squeeze from master (0be3a4c) for Postgresql 11 and it's been working great for resolving our bloat issue. However, I have just noticed that it appears to be running tasks outside of the scheduled times.

This afternoon at 15:09 I deleted ~95 million rows from a table (`anon_table_a`) and at 15:10 the squeeze worker squeezed that table.

```
# SELECT * FROM squeeze.log;
 tabschema |   tabname    |            started            |           finished            
-----------+--------------+-------------------------------+-------------------------------
 public    | anon_table_a | 2020-06-24 09:46:40.831151+01 | 2020-06-24 09:54:08.416354+01
 public    | anon_table_c | 2020-06-26 22:58:23.275731+01 | 2020-06-26 22:58:28.436476+01
 public    | anon_table_a | 2020-07-01 15:10:18.912174+01 | 2020-07-01 15:14:20.960102+01
```

The issue is that it's scheduled to be squeezed between 22:00 and 07:00:

```
# SELECT * FROM squeeze.tables;
 id | tabschema |   tabname    | clustering_index | rel_tablespace | ind_tablespaces |         schedule          | free_space_extra | min_size | vacuum_max_age | max_retry | skip_analyze 
----+-----------+--------------+------------------+----------------+-----------------+---------------------------+------------------+----------+----------------+-----------+--------------
  1 | public    | anon_table_a |                  |                |                 | {22:00:00+01,07:00:00+01} |               20 |        8 | 01:00:00       |         0 | f
  2 | public    | anon_table_b |                  |                |                 | {22:00:00+01,07:00:00+01} |               20 |        8 | 01:00:00       |         0 | f
  3 | public    | anon_table_c |                  |                |                 | {22:00:00+01,07:00:00+01} |               20 |        8 | 01:00:00       |         0 | f
```

Now that I'm writing this I also notice that the first time that table was squeezed was also outside of the defined schedule.

Have I misconfigured, or perhaps misunderstood, something? Why are these tasks being run outside of the scheduled hours?

**Comment by ahouska** [comment]
The schedule {22:00:00+01,07:00:00+01} means that the table should be processed at 7:00 and at 22:00.

As for the first schedule, I think the table will be processed immediately if it's scheduled for a time that has already passed. Do you still see out-of-schedule records in the squeeze.log table, or have only seen the problem for the initial run for each table?

**Comment by adamjforster** [comment]
> The schedule {22:00:00+01,07:00:00+01} means that the table should be processed at 7:00 and at 22:00.

Thank you for clarifying that. I had read it as they would be processed at some point _between_ the defined times, not _at_ the defined times.

> As for the first schedule, I think the table will be processed immediately if it's scheduled for a time that has already passed.

That does match what I have seen for the initial runs.

> Do you still see out-of-schedule records in the squeeze.log table, or have only seen the problem for the initial run for each table?

Yes, based on my new understanding of how the schedule works, **none** of the runs have been on schedule:

```
# SELECT * FROM squeeze.log;
 tabschema |   tabname    |            started            |           finished            
-----------+--------------+-------------------------------+-------------------------------
 public    | anon_table_a | 2020-06-24 09:46:40.831151+01 | 2020-06-24 09:54:08.416354+01
 public    | anon_table_c | 2020-06-26 22:58:23.275731+01 | 2020-06-26 22:58:28.436476+01
 public    | anon_table_a | 2020-07-01 15:10:18.912174+01 | 2020-07-01 15:14:20.960102+01
 public    | anon_table_c | 2020-07-03 22:58:58.679153+01 | 2020-07-03 22:59:03.805736+01
 public    | anon_table_c | 2020-07-10 22:58:43.08774+01  | 2020-07-10 22:58:48.579526+01
(5 rows)
```

The latest two runs have happened 58 minutes late.

**Comment by ahouska** [comment]
Have you customized the `squeeze.worker_naptime` configuration variable, or are you using the default value?

**Comment by ahouska** [comment]
I think the cause of the problem could be that the table wasn't bloated enough at 22:00, but reached the "critical" amount of free space those 58 minutes later. pg_squeeze obviously shouldn't process it in such a case.

I intend to fix the problem during rework of the scheduling mechanism, hopefully by the PG 13 release date. If you can't tolerate the current behavior, please call the squeeze.squeeze_table() function from a client application instead of using the pg_squeeze's scheduling mechanism.

**Comment by adamjforster** [comment]
Thanks @ahouska.

No, I didn't customise anything.

To be honest I'm content to live with it as is now that I understand what's going on, and I'm glad I was able to highlight an issue even though I'd misunderstood how the schedule is meant to work 😄 

Interestingly I'm running the same build on two other servers, with two different databases, but with the same schedule definitions (different tables). On those DBs the jobs have all started within 60 seconds on either 07:00 or 22:00.

As you've mentioned that you're going to look at reworking the schedule mechanism I'll leave this issue open, but please feel free to close it that's better for you.

**Comment by ahouska** [comment]
pg_squeeze 1.3 has the scheduling reworked: https://github.com/cybertec-postgresql/pg_squeeze/tree/REL1_3

It's still a beta version, please test if you can.
