### ISSUE TITLE
Pg_squeeze with EDB Advanced Server?

### ISSUE THREAD

**Issue by DHorneDBA** [cybertec-postgresql/pg_squeeze#38]
Sorry for such a basic question and I am new to postgres. This is not so much an issue as just my lack of knowledge. Trying to get pg_squeeze extension working that we downloaded from community yum.repostitory build against EDB Advanced Server 11, but run into this error. Can anyone assist on what this means?

FATAL:  incompatible library "/usr/edb/as11/lib/pg_squeeze.so": magic block mismatch
DETAIL:  Server has FUNC_MAX_ARGS = 256, library has 100.

**Comment by ahouska** [comment]
I don't know. Can you install other extensions from the community repository?

**Comment by devrimgunduz** [comment]
@DHorneDBA you need to build your own RPM, or compile from source. EDB does not support pg_squeeze.
