### ISSUE TITLE
CREATE EXTENSION pg_squeeze ERROR

### ISSUE THREAD

**Issue by malcika** [cybertec-postgresql/pg_squeeze#40]
Hi, please can you help me?
When I type the command CREATE EXTENSION pg_squeeze I get an error:
ERROR:  type "minute[]" does not exist.
Thanks

**Comment by ahouska** [comment]
How exactly have you installed the package? yum repository or build from source? Which version?

**Comment by malcika** [comment]
Build from source, the latest version.
git clone https://github.com/cybertec-postgresql/pg_squeeze.git
make
make install
And I changed postgresql.conf file 
wal_level = logical
max_replication_slots = 10
shared_preload_libraries = 'pg_squeeze'

**Comment by ahouska** [comment]
I've fixed the problem, but the fix is not in the yum repository yet. Please get the 1.3 branch source from the repository (https://github.com/cybertec-postgresql/pg_squeeze/tree/REL1_3) and build it according to README.

**Comment by malcika** [comment]
Thanks a lot. It's working now.
