### ISSUE TITLE
Monitoring squeeze

### ISSUE THREAD

**Issue by Dsolik** [cybertec-postgresql/pg_squeeze#44]
Tell me what sql query can make sure squeeze is running?

**Comment by Dsolik** [comment]
Can I use the following query for monitoring: select count(*) from pg_stat_activity where wait_event='Extension' and query like '%squeeze.tasks%'; 0 - squeeze not runing, 1 - squeeze runing

**Comment by ahouska** [comment]
I don't think this is the best way because even the "scheduler worker" accesses the "tasks" table. If you're checking for the actual squeezing, the query should contain the function name "squeeze_table".

**Comment by Dsolik** [comment]
For unknown reasons, squeeze stops working, and the tables begin to bloat, if you squeeze.start, then squeeze begins to work. I want to track the moments when squeeze stops working.

**Comment by ahouska** [comment]
The PG server log is the first thing you need to check. Do you see any errors around the time pg_squeeze stops working?

**Comment by ahouska** [comment]
There's actually more to check: the tables `squeeze.log` and `squeeze.errors`.

**Comment by kovmir** [comment]
Answered, stale.
