### ISSUE TITLE
Feature request: simple pattern matching for schema names

### ISSUE THREAD

**Issue by vmihailenco** [cybertec-postgresql/pg_squeeze#45]
E.g.

```
SELECT squeeze.squeeze_table('shard*', 'pgbench_accounts', null, null, null);
```

should process `pgbench_accounts` table in all schemas matching `shard*`. Just like `\dt+ shard*.pgbench_accounts` works for listing the tables.

**Comment by ahouska** [comment]
I don't think this is worth the effort. Also, it's not trivial to define what the function output should look like. Should it return names of tables whose name matches the pattern, or only tables processed? Should a failure to process a single table make the whole batch fail? And what if the other parameters (NULL in your example) should be different across tables?

If you need batch processing, it's not too difficult to write a query that calls the squeeze_table() function.

**Comment by vmihailenco** [comment]
I actually meant to use it with INSERT

```
INSERT INTO squeeze.tables
(tabschema, tabname, schedule, free_space_extra, vacuum_max_age,
max_retry)
VALUES ('shard*', 'bar', ('{30}', '{22}', NULL, NULL, '{3, 5}'), 30,
'2 hours', 2);
```

>Should it return names of tables whose name matches the pattern, or only tables processed?

Either would be fine. Only processed tables would be better.

>it's not too difficult

That is true for lots of features in Postgres including pattern matching for identifiers. But it is difficult / annoying to work with thousands of tables.

**Comment by df7cb** [comment]
I don't think we'd want patterns in the table, but you can use patterns to (statically) fill the table using SQL:

```
insert into squeeze.tables (tabschema, tabname, ...)
select schemaname, tablename, ... from pg_tables
where schemaname like 'shard%';
```
