### ISSUE TITLE
Probleme install pg_squezze in step make

### ISSUE THREAD

**Issue by mrhassan60** [cybertec-postgresql/pg_squeeze#46]
Hello,

I'm trying to install pg_squeeze in Ubuntu 16.04 and I'm using Postgresql 9.6 or 9.4
I am stuck at the make step, the errors are:

- make: --pgxs: command not found
make: *** No target. Stop.

- gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision = standard -g -g - O2 -fstack-protector-strong -Wformat -Werror = format-security -fPIC -pie -fno-omit-frame-pointer -fPIC -I. -I./ -I / usr / include / postgresql / 9.6 / server -I / usr / include / postgresql / internal -Wdate-time -D_FORTIFY_SOURCE = 2 -D_GNU_SOURCE -I / usr / include / libxml2 -I / usr / include / mit-krb5 -c -o pg_squeeze.o pg_squeeze.c
In file included from pg_squeeze.h: 12: 0,
                 from pg_squeeze.c: 10:
/usr/include/postgresql/internal/c.h:49:26: fatal error: postgres_ext.h: No such file or folder
compilation terminated.
<internal command>: recipe for target "pg_squeeze.o" failed
make: *** [pg_squeeze.o] Error 1

- sometimes i have errror 127

i add in file Makefile : PGCONFIG=/usr/bin/pg_config or export PGCONFIG=/usr/bin/pg_config in CLI Ubuntu 
I dont know what is problem and use command git clone  https://github.com/cybertec-postgresql/pg_squeeze.git, wget https://github.com/cybertec-postgresql/pg_squeeze/archive/REL1_0_PG_9_6.tar.gz or git clone -b REL1_0_PG_9_6 https://github.com/cybertec-postgresql/pg_squeeze.git 

Best regard
mrhasan60

**Comment by ahouska** [comment]
pg_squeeze requires postgres version 10 or higher.

**Comment by mrhassan60** [comment]
I still have the same concerns with postgresql 11

**Comment by ahouska** [comment]
It seems you're still trying to use pg_squeeze 1.0. Please try 1.3.1: https://github.com/cybertec-postgresql/pg_squeeze/releases/tag/REL1_3_1

**Comment by mrhassan60** [comment]
Always the same problem,
here are the commands i write on linux with pg_squezze 

wget https://github.com/cybertec-postgresql/pg_squeeze/archive/REL1_3_1.tar.gz
tar -zxvf REL1_3_1.tar.gz
cd pg_squeeze-REL1_3_1/
nano Makefile

#ADD in file Makefile : 

PGCONFIG=/usr/bin/pg_config

service postgresql restart
make
# the errors is : 

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pg_squeeze.o pg_squeeze.c
In file included from pg_squeeze.c:10:0:
pg_squeeze.h:12:10: fatal error: c.h: No such file or directory
 #include "c.h"
          ^~~~~
compilation terminated.
<builtin>: recipe for target 'pg_squeeze.o' failed
make: *** [pg_squeeze.o] Error 1

**Comment by dynelow** [comment]
Hi, 
having the same issue with postgresql 13 on ubuntu 20.04. Any clue please?

hello@dynlow-virtual-machine:~/build/pg_squeeze-REL1_4_1$ make && sudo make install
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/13/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pg_squeeze.o pg_squeeze.c
In file included from pg_squeeze.c:10:
pg_squeeze.h:12:10: fatal error: c.h: No such file or directory
   12 | #include "c.h"
      |          ^~~~~
compilation terminated.
make: *** [<builtin>: pg_squeeze.o] Error 1

**Comment by ahouska** [comment]
Does the file `c.h` exist either in `/usr/include/postgresql/13/server/`  or in `/usr/include/postgresql/internal/` ?

**Comment by dynelow** [comment]
I installed postgresql-server-dev 13, and it worked.
