### ISSUE TITLE
Problem to start the backgroud worker

### ISSUE THREAD

**Issue by dangill1** [cybertec-postgresql/pg_squeeze#48]
Hi,

I work with pg_squeeze 1.3 on postgres 11.4 and linux 7.9
I Installed pg_squeeze with with the rpm pg_squeeze_11-1.3.1-1.rhel7.x86_64

Now I inserted a row into the table squeeze.tables 

 id | tabschema |      tabname       | clustering_index | rel_tablespace | ind_tablespaces | free_space_extra | min_size | vacuum_max_age | max_retry | skip_analyze |   schedule
----+-----------+--------------------+------------------+----------------+-----------------+------------------+----------+----------------+-----------+--------------+--------------
  1 | xxxxx   | xxxxxxxxx |                  |                |                 |               50 |        8 | 01:00:00       |         0 | f            | ({0},{9},,,)

And I start the backgroud worker with

xxxxxxxx=# SELECT squeeze.start_worker();
 start_worker
--------------
        18225
(1 row)

But in the Postgres log there is this error  

2021-06-25 14:08:09.468 CEST [18225-1] @ (client=; app=) ERROR:  function squeeze.add_new_tasks() does not exist at character 8
2021-06-25 14:08:09.468 CEST [18225-2] @ (client=; app=) HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2021-06-25 14:08:09.468 CEST [18225-3] @ (client=; app=) QUERY:  SELECT squeeze.add_new_tasks()
2021-06-25 14:08:09.470 CEST [42398-10] @ (client=; app=) LOG:  background worker "squeeze worker for database xxxxxxxx" (PID 18225) exited with exit code 1

I'm doing something wrong ?

Many Thanks for your answer and Regards
Daniel

**Comment by ahouska** [comment]
Is this a fresh installation, or did you have older version of pg_squeeze installed? If the latter, please make sure that you run 

`ALTER EXTENSION pg_squeeze UPDATE;`

**Comment by dangill1** [comment]
The rpm of version 1.0 was well installed but not the configuration (create extension and so...) was not yet done. I installed the rpm of the 1.3 which made obsolete the 1.0

But before starting the worker I launched the update command and I received this 

xxxxxxxx=# ALTER EXTENSION pg_squeeze UPDATE;
NOTICE:  version "1.3" of extension "pg_squeeze" is already installed
ALTER EXTENSION

Can there still be something from 1.0 rpm on the server?

**Comment by dangill1** [comment]
Hi,

Close by error. Can anyone help for this issue ?

Thanks and regards

**Comment by ahouska** [comment]
Well, the `squeeze.add_new_tasks()` function is in version 1.2 but not 1.3. So the shared library your server uses is probably from version 1.2. Please check to which RPM the file `lib/pg_squeeze.so` in your installation belongs. Or is it possible that you installed the v1.3 RPM and then also installed v1.2 from source code to the same location?

**Comment by dangill1** [comment]
Hi ahouska,

The shared library is from the V1.3 :

```
/home/postgres > rpm -qf /usr/pgsql-11/lib/pg_squeeze.so
pg_squeeze_11-1.3.1-1.rhel7.x86_64
```

and we installed the V1.3 RPM on the V1.2 RPM and we dont install from source.

thanks

**Comment by ahouska** [comment]
Which version is specified in `share/extension/pg_squeeze.control` ?

**Comment by dangill1** [comment]
Hi ahouska,
The version of share/extension/pg_squeeze.control is also V1.3 but i noticed that the vm was rebooted last weekend and tried to restart the worker that is now working.
Many thanks for your help and Regards
Daniel
