### ISSUE TITLE
Scheduling pg_squeeze not working

### ISSUE THREAD

**Issue by Bader72** [cybertec-postgresql/pg_squeeze#49]
Hello every body,

I had installing pg_squeeze 1.3.1 on PostgreSQL 10.5 whith RedHat 7.6.
I would like to schedule squeeze bloat table but this do not work.
1- I had create table "t_test"

```
mydb=# \d+ t_test
                                  Table "squeeze.t_test"
 Column |  Type   | Collation | Nullable | Default | Storage | Stats target | Description
--------+---------+-----------+----------+---------+---------+--------------+-------------
 id     | integer |           | not null |         | plain   |              |
Indexes:
    "t_test_pkey" PRIMARY KEY, btree (id)
mydb=# select count(*) from t_test;
  count
---------
 2000000
(1 row)
```
2- I had update all colomns ==> t_test table is bloated now.
3- parameter is setting:
```
mydb=# select name,setting  from pg_settings where name like '%squeeze.worker%';
           name           | setting
--------------------------+----------
 squeeze.worker_autostart | mydb
 squeeze.worker_role      | postgres
(2 rows)
```
4- squeeze is up 
```
mydb=# \! ps fu -C postgres | grep squeeze
postgres 28109  0.0  0.3 1359496 10248 ?       Ss   Aug16   0:45  \_ postgres: bgworker: pg_squeeze squeeze worker for database mydb
postgres 28110  0.0  0.2 1359536 9232 ?        Ss   Aug16   0:45  \_ postgres: bgworker: pg_squeeze scheduler worker for database mydb
```
5- schedule time is added to squeeze.table 
```
mydb=# select * from squeeze.tables\gx
id               | 1
tabschema        |  squeeze
tabname          | t_test
clustering_index |
rel_tablespace   |
ind_tablespaces  |
free_space_extra | 90
min_size         | 8
vacuum_max_age   | 00:10:00
max_retry        | 0
skip_analyze     | f
schedule         | ({31},{15},,,"{1,2,3,4,5,6,7}")
```
==> i had increasing/decreasing many times "free_space_extra, min_size and vacuum_max_age" values and looking after to test but nothing better!
6- nothing in "tasks, log and errors" tables not in pg_log either for pg_squeeze. (note "log_min_duration_statement = '0'")
7- however when i do "select squeeze.squeeze_table('squeeze','t_test', null, null, null);"
"t_test" is squeezed and table size goes from 138 MB to 69 MB.

*** My question is had i forgot some thing. Please help!
Thanks

**Comment by ahouska** [comment]
Does the table appear in the `squeeze.scheduled_for_now` view at the time specified in `squeeze.tables(schedule)`?

**Comment by Bader72** [comment]
No, nothing il this table:
pgercm=# select * from squeeze.scheduled_for_now;
 table_id | tabschema | tabname
----------+-----------+---------
(0 rows)

but tow in table "squeeze.tables"
pgercm=# select * from squeeze.tables\gx
-[ RECORD 1 ]----+--------------------------------
id               | 2
tabschema        |  squeeze
tabname          | dba_table
clustering_index |
rel_tablespace   |
ind_tablespaces  |
free_space_extra | 2
min_size         | 8
vacuum_max_age   | 00:01:00
max_retry        | 0
skip_analyze     | f
schedule         | ({30},{20},,,"{1,2,3,4,5,6,7}")
-[ RECORD 2 ]----+--------------------------------
id               | 1
tabschema        |  squeeze
tabname          | t_test
clustering_index |
rel_tablespace   |
ind_tablespaces  |
free_space_extra | 90
min_size         | 8
vacuum_max_age   | 00:10:00
max_retry        | 0
skip_analyze     | f
schedule         | ({41},{9},,,"{1,2,3,4,5,6,7}")

Thanks

**Comment by ahouska** [comment]
Please send me the exact contents of the "schedule" column (the listing above contains some dots) an also the output of `SELECT now()` at the moment you expect the squeezing to happen.

**Comment by Bader72** [comment]
Hi Ahouska,
Thank yo for answer.
Tis is informations asked for:
pgercm=# SELECT *, (schedule).* FROM squeeze.tables\gx
-[ RECORD 1 ]----+--------------------------------
id               | 1
tabschema        |  squeeze
tabname          | t_test
clustering_index |
rel_tablespace   |
ind_tablespaces  |
free_space_extra | 10
min_size         | 8
vacuum_max_age   | 00:10:00
max_retry        | 0
skip_analyze     | f
schedule         | ({26},{11},,,"{1,2,3,4,5,6,7}")
minutes          | {26}
hours            | {11}
days_of_month    |
months           |
days_of_week     | {1,2,3,4,5,6,7}
-[ RECORD 2 ]----+--------------------------------
id               | 2
tabschema        |  squeeze
tabname          | dba_table
clustering_index |
rel_tablespace   |
ind_tablespaces  |
free_space_extra | 2
min_size         | 8
vacuum_max_age   | 00:01:00
max_retry        | 0
skip_analyze     | f
schedule         | ({30},{20},,,"{1,2,3,4,5,6,7}")
minutes          | {30}
hours            | {20}
days_of_month    |
months           |
days_of_week     | {1,2,3,4,5,6,7}

** I had done this shell:
#!/bin/sh
SECONDS=0
while [[ SECONDS -lt 60 ]] ; do
psql pgercm << DBA >> log.test
select now();
SELECT pg_size_pretty(pg_relation_size('squeeze.t_test'));
DBA
done

==> tis is the result:
***begin of file*****
-------------------------------
 2021-08-20 11:26:05.471279+02
(1 row)

 pg_size_pretty
----------------
 138 MB
(1 row)

              now
-------------------------------
 2021-08-20 11:26:05.494271+02
(1 row)

 pg_size_pretty
----------------
 138 MB
(1 row)

              now
-------------------------------
 2021-08-20 11:26:05.503251+02
(1 row)

 pg_size_pretty
----------------
 138 MB
(1 row)

              now
-------------------------------
 2021-08-20 11:26:05.511548+02
(1 row)

 pg_size_pretty
----------------
 138 MB
(1 row)

              now
-------------------------------
 2021-08-20 11:26:05.519654+02
(1 row)

 pg_size_pretty
----------------
 138 MB
(1 row)

....
end of file
-------------------------------
 2021-08-20 11:27:04.969542+02
(1 row)

 pg_size_pretty
----------------
 138 MB
(1 row)

              now
-------------------------------
 2021-08-20 11:27:04.977251+02
(1 row)

 pg_size_pretty
----------------
 138 MB
(1 row)

              now
-------------------------------
 2021-08-20 11:27:04.984968+02
(1 row)

 pg_size_pretty
----------------
 138 MB
(1 row)

              now
-------------------------------
 2021-08-20 11:27:04.992747+02
(1 row)

 pg_size_pretty
----------------
 138 MB
(1 row)

              now
-------------------------------
 2021-08-20 11:27:05.000603+02
(1 row)

 pg_size_pretty
----------------
 138 MB
(1 row)

***** i had check the table with check_postgres.pl:
[server01]$check_postgres_bloat -v --db pgercm --warning='10 M' --critical='20 M'
POSTGRES_BLOAT CRITICAL: DB "pgercm" (host:localhost) (db pgercm) 
table squeeze.t_test rows:2000000 
pages:17700 shouldbe:8811 (2.0X) 
wasted size:72818688 (69 MB) | squeeze.t_test=72818688B 
t_test_pkey=12869632B 
pg_catalog.pg_attribute=237568B 
pg_depend_depender_index=221184B 
pg_depend_reference_index=180224B 
public.spatial_ref_sys=139264B 
pg_catalog.pg_depend=49152B 
pg_class_tblspc_relfilenode_index=32768B 
pg_amproc_fam_proc_index=16384B 
pg_amproc_oid_index=16384B 
pg_catalog.pg_class=16384B 
pg_catalog.pg_constraint=16384B 
pg_catalog.pg_amproc=8192B 
pg_attribute_relid_attnam_index=0B 
pg_attribute_relid_attnum_index=0B 
pg_constraint_oid_index=0B 
spatial_ref_sys_pkey=0B

Best regards 
Bader

**Comment by pashagolub** [comment]
@Bader72 would you please use formatting next time. It helps developers a lot. Thanks in advance!

**Comment by ahouska** [comment]
The `now()` function shows time from `2021-08-20 11:26:05.471279+02` to `2021-08-20 11:27:05.000603+02` but the scheduled time seems to be `20:30`. Why do you think this particular schedule should be active around `11:26`?

**Comment by Bader72** [comment]
Hi Ahouska,
Thank you for replay. 
The relation (table) that i want to squeeze, is "t_test" table with "id =1". It should be squeezed at 11:26.
the schedule time 20:30 is for "dba_table" with "id=2".
Best regards

**Comment by ahouska** [comment]
I see, sorry for the confusion. Anyway, please to run `TABLE squeeze.scheduled_for_now` instead of calling `pg_size_pretty().` First we need to know if time checking is the issue or if the task is created but skipped for another reason.

**Comment by Bader72** [comment]
table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:20:43.516128+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:20:43.528271+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:20:43.540448+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
             now
...................................
 2021-08-24 11:20:43.55292+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:20:43.565198+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
             now
...................................
 2021-08-24 11:20:43.57785+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:20:43.590336+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:20:43.602759+02
(1 row)
*******              now
...................................
 2021-08-24 11:21:42.859137+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:21:42.871847+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:21:42.884542+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:21:42.897199+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:21:42.909727+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:21:42.922317+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:21:42.934935+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:21:42.947523+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:21:42.960253+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:21:42.972934+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:21:42.985845+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)
              now
...................................
 2021-08-24 11:21:43.000679+02
(1 row)

 table_id | tabschema | tabname
+----------+-----------+---------+
(0 rows)

**Comment by ahouska** [comment]
So something seems to be wrong about the `squeeze.scheduled_for_now view`. (I suppose you adjusted the schedule so it matched the system time during the test.)

Can you please check if there's a record for your table in `tables_internal`? Maybe using this query:

`select t.tabschema, t.tabname, ti.*
from squeeze.tables_internal ti, squeeze.tables t 
where ti.table_id=t.id and t.tabname='t_test';`

**Comment by omer414** [comment]
I am having the exact same problem. I have added a new schedual for table, it should ideally run every 30 mins but it has never run. I can do manual squeeze without any problem. Is there any cronjob etc that need to be added in order for the schedule to work?

```
>> select * from squeeze.tables\gx
-[ RECORD 1 ]----+-----------
id               | 1
tabschema        | public
tabname          | events
clustering_index | 
rel_tablespace   | 
ind_tablespaces  | 
free_space_extra | 50
min_size         | 8
vacuum_max_age   | 01:00:00
max_retry        | 0
skip_analyze     | f
schedule         | ({30},,,,)

```

**Comment by omer414** [comment]
@Bader72 did you manage to get the schedule working?

**Comment by Bader72** [comment]
Hi omer414, hi ahouska

Thanks for replay.
I hadn't continued my test bescause i had changed tests for pg_repack because i had waited for help!
i'll continue my tests with pg_squeeze now but i shoud prepare my environement again.
Thanks for all af you

**Comment by ahouska** [comment]
@omer414, like I asked @Bader72, can you please check if there's a record for your table in `tables_internal`?

`select t.tabschema, t.tabname, ti.* from squeeze.tables_internal ti, squeeze.tables t where ti.table_id=t.id and t.tabname='t_test';`

Also please check the contents of the tables squeeze.log and squeeze.errors.

Finally make sure that the background workers are running (SELECT squeeze.start_worker() is the command to start them, unless you have set the `squeeze.worker_autostart` configuration parameter.

**Comment by omer414** [comment]
```
> SELECT t.tabschema, t.tabname, ti.* from squeeze.tables_internal ti, squeeze.tables t where ti.table_id=t.id and t.tabname='events';
 tabschema | tabname | table_id | last_task_finished 
-----------+---------+----------+--------------------
 public    | events  |        1 | 
(1 row)

> SELECT * FROM squeeze.log;
 tabschema | tabname | started | finished 
-----------+---------+---------+----------
(0 rows)

> SELECT * FROM squeeze.errors;
 id | occurred | tabschema | tabname | sql_state | err_msg | err_detail 
----+----------+-----------+---------+-----------+---------+------------
(0 rows)

```

So i have tried to start the worker but it always returns 0, currently i have setup squeeze.worker_autostart in postrges.conf. But even when i havn't had squeeze.worker_autostart setup, start_worker() still returned 0.

```
> SELECT squeeze.start_worker();
 start_worker 
--------------
            0
(1 row)
```

**Comment by ahouska** [comment]
It's o.k. for start_worker() to return 0.

Please check the view `squeeze.scheduled_for_now` at the moment you think the table should be processed. If your table is not there, please send me the contents of the `squeeze.tables(schedule)` column as well as the result of `SELECT now()`.

**Comment by omer414** [comment]
```
> SELECT * FROM squeeze.scheduled_for_now;
 table_id | tabschema | tabname 
----------+-----------+---------
(0 rows)

> SELECT * FROM squeeze.tables(schedule);
ERROR:  column "schedule" does not exist
LINE 1: SELECT * FROM squeeze.tables(schedule);

> SELECT now();
              now              
-------------------------------
 2021-11-05 15:16:28.842753+05
```

**Comment by ahouska** [comment]
If the schedule is `({30},,,,)`, then I wouldn't expect the table to appear in the `squeeze.scheduled_for_now` if the current time is `15:16:28.842753+05`.  What I'm trying to check is if the table appears in `scheduled_for_now` at the moment `SELECT EXTRACT(minute FROM now())` is returning the value 30.

**Comment by omer414** [comment]
So here are the details of what you asked for. 

```
> SELECT EXTRACT(minute FROM now());
 date_part 
-----------
        28
(1 row)

> SELECT * FROM squeeze.scheduled_for_now;
 table_id | tabschema | tabname 
----------+-----------+---------
(0 rows)

> SELECT EXTRACT(minute FROM now());
 date_part 
-----------
        29
(1 row)

> SELECT * FROM squeeze.scheduled_for_now;
 table_id | tabschema | tabname 
----------+-----------+---------
(0 rows)

> SELECT EXTRACT(minute FROM now());
 date_part 
-----------
        30
(1 row)

> SELECT * FROM squeeze.scheduled_for_now;
 table_id | tabschema | tabname 
----------+-----------+---------
        1 | public    | events
(1 row)

> SELECT EXTRACT(minute FROM now());
 date_part 
-----------
        31
(1 row)

> SELECT * FROM squeeze.scheduled_for_now;
 table_id | tabschema | tabname 
----------+-----------+---------
(0 rows)

```

**Comment by ahouska** [comment]
Thanks.` So the view appears to work. Can you please now run this query

`select tb.tabname from squeeze.tables tb, squeeze.tasks tsk where tsk.table_id=tb.id;`

at the time the `events` table name is present in the `squeeze.scheduled_for_now` view? If `events` does not, appear in the result, please set `log_min_messages` to `debug1`, restart the server and check if and how often this message appears in the log

`scheduler worker: checking the schedule`

**Comment by ahouska** [comment]
Wait, this might be a better approach:

1. Stop the background workers (`select squeeze.stop_worker()`)
2. Adjust the schedule and wait until your table appears in `squeeze.scheduled_for_now` - just like you did last time.
3. While the schedule time is still there, run `select squeeze.check_schedule();`
4. run tnis query
    `select tb.tabname, tsk.* from squeeze.tables tb, squeeze.tasks tsk where tsk.table_id=tb.id;`
5. run `select squeeze.dispatch_new_tasks();`
6. again
    `select tb.tabname, tsk.* from squeeze.tables tb, squeeze.tasks tsk where tsk.table_id=tb.id;`

**Comment by ahouska** [comment]
And one more suggestion, before you turn off the workers: try to set the `free_space_extra` and `min_size` columns of `squeeze.tables` to zero and check if they get processed now. If it helps, try to find the appropriate non-zero values so that the table is not processed more often than necessary.

**Comment by omer414** [comment]
@ahouska I was able to set free_space_extra to 0 but cannot set min_size to 0. 

```
> Update squeeze.tables SET min_size = 0 WHERE tabname = 'events';
ERROR:  new row for relation "tables" violates check constraint "tables_min_size_check"
DETAIL:  Failing row contains (1, public, events, null, null, null, 0, 0, 01:00:00, 0, f, ({30},,,,)).

```

**Comment by omer414** [comment]
@ahouska so i have made some changes. I have set squeeze.table to run every 10 mins instead of 30 min. 


```
> SELECT EXTRACT(minute FROM now());
-[ RECORD 1 ]
date_part | 7

> select squeeze.check_schedule();
-[ RECORD 1 ]--+-
check_schedule | 

> SELECT * FROM squeeze.scheduled_for_now;
(0 rows)

> select tb.tabname, tsk.* from squeeze.tables tb, squeeze.tasks tsk where tsk.table_id=tb.id;
(0 rows)

==========================================

> SELECT EXTRACT(minute FROM now());
-[ RECORD 1 ]-
date_part | 10

> select squeeze.check_schedule();
-[ RECORD 1 ]--+-
check_schedule | 

> SELECT * FROM squeeze.scheduled_for_now;
-[ RECORD 1 ]-----
table_id  | 1
tabschema | public
tabname   | events

> select tb.tabname, tsk.* from squeeze.tables tb, squeeze.tasks tsk where tsk.table_id=tb.id;
-[ RECORD 1 ]-----------------------------
tabname    | events
id         | 35
table_id   | 1
created    | 2021-11-11 16:10:43.811595+05
free_space | 
tried      | 0
state      | new

> select squeeze.dispatch_new_tasks();
-[ RECORD 1 ]------+-
dispatch_new_tasks | 

> select tb.tabname, tsk.* from squeeze.tables tb, squeeze.tasks tsk where tsk.table_id=tb.id;
-[ RECORD 1 ]-----------------------------
tabname    | events
id         | 35
table_id   | 1
created    | 2021-11-11 16:10:43.811595+05
free_space | 44.68603705478321
tried      | 0
state      | ready

```

**Comment by ahouska** [comment]
If the state is `ready`, then the table should be squeezed as soon as you star the background worker.

What helped? Have you adjusted the `free_space_extra` setting.
