### ISSUE TITLE
RAM requirements

### ISSUE THREAD

**Issue by vmihailenco** [cybertec-postgresql/pg_squeeze#5]
I am getting following error in squeeze.errors when I am trying to squeeze 5GB table on server that has 3.5GB RAM (~500MB are reported to be free):

```
53200     | out of memory | Failed on request of size 2551
```

Log

```
2017-06-12 11:05:08 UTC [15483-1] LOG:  logical decoding found consistent point at 643/DC001558
2017-06-12 11:05:08 UTC [15483-2] DETAIL:  There are no running transactions.
2017-06-12 11:05:08 UTC [15483-3] CONTEXT:  SQL statement "SELECT squeeze.squeeze_table(v_tabschema, v_tabname,
         v_cl_index, v_rel_tbsp, v_ind_tbsps, v_autovac, v_autovac_toast)"
        PL/pgSQL function squeeze.process_current_task() line 43 at PERFORM
        SQL statement "SELECT squeeze.process_current_task()"
TopMemoryContext: 147024 total in 6 blocks; 73240 free (88 chunks); 73784 used
...
Grand total: 567637936 bytes in 348 blocks; 301691896 free (235427 chunks); 265946040 used
```

So I wonder how much RAM pg_squeeze requires...

**Comment by bryanconlon** [comment]
I am trying to use it on a large 123GB table and I am getting: "invalid memory alloc request size 1073741824"

**Comment by ahouska** [comment]
@bryanconlon 1. what's your value of maintenance_work_mem?, 2. Do you get the error even if you run the squeeze.squeeze_table() function manually and pass a clustering index as the 3rd argument? (Table schema and name are passed as the 1st and 2nd arguments respectively. The 4th and 5th arguments can be NULL, the 6th and 7th tell whether autovacuum should stay enabled on the table and its TOAST relation respectively when the function exits.) Note: Before you run the function, you need to set the user_catalog_table option on it, e.g. ALTER TABLE foo SET (user_catalog_table = true)

**Comment by ahouska** [comment]
@vmihailenco 1. what are your values of work_mem and maintenance_work_mem?, 2. Do you get the error even if you set the "clustering_index" in squeeze.tables for the table that causes the failure?

**Comment by vmihailenco** [comment]
They were reasonably small to fit into RAM (work_mem ~ 1/8 RAM, maintenance_work_mem ~1/16), i.e. pg_repack was able to finish without any issues.

**Comment by ahouska** [comment]
@vmihailenco I wonder if the message

Grand total: 567637936 bytes in 348 blocks; 301691896 free (235427 chunks); 265946040 used

corresponds to your statement about ~500MB of free RAM. Doesn't it help if you decrease maintenance_work_mem? pg_squeeze tries not to exceed this limit. Besides that, the updates I've just pushed could reduce the memory consumption.

**Comment by ahouska** [comment]
@bryanconlon I suspect that the "invalid memory alloc request size 1073741824" error is related to the storage (array) that pg_squeeze uses to copy data from the existing to the new table. The new releases spend additional effort to avoid this problem.
