### ISSUE TITLE
Disk space requirements of pg_squeeze?

### ISSUE THREAD

**Issue by larskanis** [cybertec-postgresql/pg_squeeze#55]
I couldn't find any information about the disk space requirements of pg_squeeze.

My hope was that it doesn't require any additional space to squeeze a table, but experimentation showed, that it needs at least the size of the table.

The readme of pg_repack tells about the space requirement [here](https://reorg.github.io/pg_repack/#requirements). Maybe you can add a sentence to the readme of pg_squeeze as well?

Background is, that our servers from time to time run out of disk space. This is because we process a lot of short term data and if we forget to adjust data deletion processes after certain schema changes, the database blows up quickly. In this case the only way to delete old records and shrink the database space, is to add more disk space at first. This is cumbersome.

**Comment by ahouska** [comment]
Indeed, it might not be obvious for an user. I've added a note to README.

**Comment by larskanis** [comment]
OK, thank you for clarification!
