### ISSUE TITLE
multiple launch of pg_squeeze

### ISSUE THREAD

**Issue by tanushka816** [cybertec-postgresql/pg_squeeze#58]
hi everybody!
I try to use pg_squeeze on two tables in my schema at the same time in different connection under different user (both have required grants). Both of tables are bloated. It goes like this: 

```
-- as admin_1
SELECT squeeze.squeeze_table('my_schema', 'table_1', null, null, null);
```
and still first query work as admin_2 I run: 

```
-- as admin_2
SELECT squeeze.squeeze_table('my_schema', 'table_2', null, null, null);
```
And I get an error in second query "replication slot "pg_squeeze_slot_16***" already exists".
As they say in https://hevodata.com/learn/postgresql-replication-slots/#log , datoid for logical replication is an  OID of the database this slot is associated with. These tables are in one database. Is there a way to handle few tables in one DB at the same time? 

At the beginning i thought it depends on amount of free replications slots, seems it's not true.
P.s. wal_level is logical, max_replication_slots = 10. If I run squeeze on one table I see row in pg_replication_slots with dataoid 16***.

**Comment by ahouska** [comment]
The slot name is the problem. I thought that one slot per database is enough since there's a single background worker per database. I'll add the relation id to the slot name in the next release.

**Comment by ahouska** [comment]
The master branch (https://github.com/cybertec-postgresql/pg_squeeze) can now process multiple tables at a time. Please try if you're still interested. (A separate branch for the new version will be created soon.)

**Comment by kovmir** [comment]
Implemented, so I close it.
