### ISSUE TITLE
RE: `pg_squeeze` is known to be compatible with MS Windows

### ISSUE THREAD

**Issue by RickeyWard** [cybertec-postgresql/pg_squeeze#64]
>`pg_squeeze` is known to be compatible with MS Windows.
To build the extension using MinGW, make sure `pg_config` is in your `$PATH`, and issue `make WIN32RES=`.

_Originally posted by @kovmir in https://github.com/cybertec-postgresql/pg_squeeze/issues/20#issuecomment-1715795825_

I have attempted to use MinGW on Ubuntu to compile for windows using `make WIN32RES=` setting CC= mingw gcc executable but I'm having trouble, are there any steps or required flags that might not be obvious?

PGXS doesn't come with the windows distribution of Postgres (and is said by the docs to be linux only) so I am assuming you meant to cross-compile from linux using the posgresql-server-dev package and MinGW. Any recommendation on which Linux distro that has the packages we need and any special steps? 2 senior and 1 junior developer at my org tried to figure out how to get this to compile with no luck, any further direction would be much appreciated.

**Comment by kovmir** [comment]
>but I'm having trouble

You must clearly specify what your trouble is, otherwise it is not possible for us to help you.
Could you please show the error messages and the precise sequence of commands leading you to the "trouble"?

Regarding my comment that you quoted... I was compiling the extension on MS Windows within MinGW shell, not any sort of cross-compilation. So, to summarize the way I did it:

1. Take a fresh MS Windows installation
2. Install MinGW
3. Run MinGW shell
4. Build and install PostgreSQL with `./configure && make && make install`
5. Also in MinGW shell, build `pg_squeeze` with `make WIN32RES= && make install`
6. Verify it passes `make installcheck`

**Comment by RickeyWard** [comment]
I didn't elaborate because I got nowhere, on windows pgxs didn't exist and on linux tons of libraries were missing (adding them one at a time eventually I couldn't find them anymore).

MinGW doesn't have a "shell",  but saying "Run MinGW shell" helped me understand that you're intending to use something like cygwin so that's what I installed and with it I added all the MinGW packages as well as all the devel packages it had to offer.

Since Cygwin offers a faux linux environment PGXS worked (even though the official docs says it doesn't work on windows) and I was able to build pg_squeeze.

@kovmir thanks for outlining the steps.

For anyone interested in how I got it to build here's the elaborated steps I took following kovmirs instructions:

1. New MS Windows 10 Pro 22H2 VM
2. fetch the source for the version of postgres I was targeting (14.9)
`curl -o postgresql-14.9.tar.gz https://ftp.postgresql.org/pub/source/v14.9/postgresql-14.9.tar.gz`
3. fetch and install cygwin
`curl -o cygwin_setup.exe http://cygwin.com/setup-x86_64.exe`
run cygwin, add archiver and I ticked all of devel which took forever to install but make sure I had all it had to offer
4. Run Cygwin Terminal
5. extract postgres source using `tar -xvf ...` available in cygwin
6. Build and install PostgreSQL with ./configure && make && make install
7. clone pg_squeeze and build it in cygwin `make WIN32RES= && make install`
    installcheck fails for me, but it still built which is what I needed.

to manual install an extension to postgres on windows

1. pg_squeeze.dll goes in {programfiles}postgres\{version}\lib\pg_squeeze.dll
2. pg_squeeze.control + .sql files go in {programfiles}postgres\{version}\share\extension\*
3. in postgresql.conf set `shared_preload_libraries = 'pg_squeeze'`
4. restart postgres, `run pg_reload_conf() as superuser`

follow pg_squeeze readme

**Comment by kovmir** [comment]
You said `make installcheck` fails. Did you include `pg_squeeze` into `shared_preload_libraries` and set the other necessary configuration options?

**Comment by kovmir** [comment]
You are right though, `MinGW` does not have a shell, it is a compiler. I meant [msys2](https://www.msys2.org/) shell.

**Comment by RickeyWard** [comment]
> You said `make installcheck` fails. Did you include `pg_squeeze` into `shared_preload_libraries` and set the other necessary configuration options?

yes, It builds but it doesn't run. If I copy the pg_squeeze.dll into windows install of postgres lib directory and the control file/sql files into the share\extension director add it to shared_preload_libraries, wal to logical, and slots at least 1 restart postgres and reload config then attempt to create the extension it fails with could not load library the specified module could not be found.

Nothing useful in the postgres logs, just a generic not found message though clearly it exists.

>2023-09-22 20:58:00.553 BST [8348] STATEMENT:  CREATE EXTENSION pg_squeeze;
2023-09-22 20:58:24.672 BST [6220] ERROR:  could not load library "C:/Program Files/PostgreSQL/14/lib/pg_squeeze.dll": The specified module could not be found.

![image](https://github.com/cybertec-postgresql/pg_squeeze/assets/342468/f456c90a-4bd9-4779-b724-1d514255b508)

**Comment by RickeyWard** [comment]
Following the steps again from scratch but using msys2 pg_squeeze no longer links after build:

```
$ make WIN32RES=
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2   -shared -static-libgcc -o pg_squeeze.dll  pg_squeeze.o concurrent.o worker.o pgstatapprox.o  -LC:/msys64/ucrt64/lib   -Wl,--allow-multiple-definition -Wl,--disable-auto-import  -Wl,--as-needed   -LC:/msys64/ucrt64/lib -lpostgres -lpgcommon -lpgport -lz -lws2_32 -lm  -lws2_32 -Wl,--export-all-symbols -Wl,--out-implib=libpg_squeeze.a
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: pg_squeeze.o:pg_squeeze.c:(.rdata$.refptr.FirstSnapshotSet[.refptr.FirstSnapshotSet]+0x0): undefined reference to `FirstSnapshotSet'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: pg_squeeze.o:pg_squeeze.c:(.rdata$.refptr.wal_segment_size[.refptr.wal_segment_size]+0x0): undefined reference to `wal_segment_size'
collect2.exe: error: ld returned 1 exit status
make: *** [C:/msys64/ucrt64/lib/POSTGR~1/pgxs/src/MAKEFI~1/../../src/Makefile.shlib:374: pg_squeeze.dll] Error 1
```

**Comment by kovmir** [comment]
@RickeyWard, I am sorry for the late response, but I have no idea how to help you.

**Comment by kovmir** [comment]
Stale. If new questions/information pops up, re-open.
