### ISSUE TITLE
pg_squeeze stop working with error "duplicate key value violates unique constraint "pg_replication_origin_roname_index""

### ISSUE THREAD

**Issue by ramkly** [cybertec-postgresql/pg_squeeze#67]
pg_squeeze was working for 4 months without any error. all of a sudden it stops working and throws the error "duplicate key value violates unique constraint "pg_replication_origin_roname_index" "
When I check squeeze.error table err_details I have "Key (roname)=(pg_squeeze_16401_412356) already exists."
I checked pg_replication_slot and I don't have any slot with this name, when I run the squeeze_table function manually, I can see squeeze create that slot with the given name, but after a few min, it throws the same error.
Any idea what could be the reason?
![image](https://github.com/cybertec-postgresql/pg_squeeze/assets/8080277/21a7f913-0a19-4b1e-b5f7-de4235e71d59)

![image](https://github.com/cybertec-postgresql/pg_squeeze/assets/8080277/43839502-b6a7-4a9b-b421-549b3c9cc3af)

![image](https://github.com/cybertec-postgresql/pg_squeeze/assets/8080277/aa7247f1-5cae-4ebf-87c0-711257a87971)

**Comment by ahouska** [comment]
1. This is a replication origin, not a slot. Please make sure `pg_squeeze` is not running (i.e. run `SELECT squeeze.stop_worker()` and check than `squeeze.get_active_workers()` returns no rows), then drop the origin this way:

`SELECT pg_replication_origin_drop('pg_squeeze_16401_412356');`

2. Please send me the last message preceding the `"duplicate key value violates unique constraint ..."` one.

3. Are you using a stable branch (REL1_6) or master?

**Comment by ramkly** [comment]
Thanks for your message, I was using a master one, and after compiling REL1_6, it got fixed
