### ISSUE TITLE
Question: can this extension be used to hyperTable of timescale?

### ISSUE THREAD

**Issue by lincoln310** [cybertec-postgresql/pg_squeeze#73]
We use timecale to store data. And hyperTable to store data in chunks automatically. 
Can i just regist the hyperTable to squeeze.tables, and apply to all it's chunks? And also the new chunks day by day?

If not, can you give me an suggest?

Well, i can write a logic to  find all the chunks every day, and add to squeeze.tables. I just want to known, if there is a better way.

**Comment by df7cb** [comment]
pg_squeeze does not know about hypertables, and even for plain partitioned tables, it wants to run only on the individual partitions. So you'll have to write some logic to work on the base tables.

**Comment by lincoln310** [comment]
> pg_squeeze does not know about hypertables, and even for plain partitioned tables, it wants to run only on the individual partitions. So you'll have to write some logic to work on the base tables.

Thanks, i will use the pa_stat_all_tables to select the tables i need.
